version: '2'
services: 
  
  web:
    build: './web'
    ports: 
      - "5000:5000"
    links: 
      - db
    depends_on: 
      - db
    volumes: 
      - './web:/usr/src/app'

  db:
    build: './db'